### ISSUE TITLE
Falta un fichero README.md

### ISSUE THREAD

**Issue by alu0100783230** [ULL-ESIT-GRADOII-PL/tareas-iniciales-EleDiaz#3]
Es necesario incluir un fichero _README.md_ dentro de cada repositorio, en este caso, con al menos un enlace al web resutante en la [rama gh-pages](https://github.com/ULL-ESIT-GRADOII-PL/tareas-iniciales-EleDiaz/tree/gh-pages). :space_invader:

**Comment by EleDiaz** [comment]
Se puesto el readme in commit 0ae8295
